### ISSUE TITLE
codebase

### ISSUE THREAD

**Issue by AItechnology** [majedelhelou/VIDIT#1]
When the codebase could be published？

**Comment by zrfanzy** [comment]
Hi,
which code do you mean?

**Comment by AItechnology** [comment]
The code from your paper

**Comment by zrfanzy** [comment]
Hi,
The paper only presents the dataset and does not have any code. The only scripts we have were some scripts to semi-automate the capture from UE, but the capture cannot be reproduced unless you purchase the environments.
