### ISSUE TITLE
Awesome list?

### ISSUE THREAD

**Issue by HongLouyemeng** [majedelhelou/VIDIT#8]
This direction is very good. It may be better to organize it into awesome list.

**Comment by majedelhelou** [comment]
Thank you! Do you want to collaborate to organize an awesome-image-relighting list?

**Comment by HongLouyemeng** [comment]
> Thank you! Do you want to collaborate to organize an awesome-image-relighting list?

yes ! I think image-relighting is very promising. I think it's not just me who is interested in it.
